---
title: "Clustering Methods"
output: html_notebook
author: "Sri Seshadri"
---

# K mediods and partion about mediod

The code is from http://www.sthda.com/english/articles/27-partitioning-clustering-essentials/88-k-medoids-essentials/#pam-concept

Standardized USArrests data is used for this exercise. The packages that we'll be using are cluster and factoextra.

# Decision on K

```{r}
library(magrittr)
df <- USArrests %>% 
  scale(.)
library(cluster)
library(factoextra)
fviz_nbclust(df, pam, method = "silhouette")
```

# K - Mediods

```{r}
pam.res <- pam(df, 2)
pam.res

fviz_cluster(pam.res, 
             palette = c("#00AFBB", "#FC4E07"), # color palette
             ellipse.type = "t", # Concentration ellipse
             repel = F, # Avoid label overplotting (slow)
             labelsize = 3,
             ggtheme = theme_classic()
             )
```

# DBSCAN

```{r}
#library(factoextra)
data("multishapes")
df <- multishapes[, 1:2]
set.seed(123)
km.res <- kmeans(df, 5, nstart = 25)
fviz_cluster(km.res, df,  geom = "point", 
             ellipse= FALSE, show.clust.cent = FALSE,
             palette = "jco", ggtheme = theme_classic())
```
```{r}
dbscan::kNNdistplot(df, k =  7)
abline(h = 0.15, lty = 2)
```

```{r}
set.seed(123)
db <- fpc::dbscan(df, eps = 0.15, MinPts = 5)
# Plot DBSCAN results
library("factoextra")
fviz_cluster(db, data = df, stand = FALSE,
             ellipse = FALSE, show.clust.cent = FALSE,
             geom = "point",palette = "jco", ggtheme = theme_classic())
```

